import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import QueryProvider from "@/lib/query-provider";
import TopNav from "@/components/TopNav";
import Footer from "@/components/web/Footer";
import ThemeProvider from "@/components/ThemeProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en" data-theme="dark" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased z-0 bg-background text-foreground`}
      >
        <ThemeProvider>
          <div className="min-h-screen overflow-x-hidden">
            <TopNav />
            <QueryProvider>{children}</QueryProvider>
            <Footer />
          </div>
        </ThemeProvider>
      </body>
    </html>
  );
}
